on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: write comment
        id: write_comment
        run: |
          echo "creating service Address_API%0Acreating route Address_API-get_list_address_data" >> $GITHUB_OUTPUT
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            ${{ steps.write_comment.outputs }}
          find: |
            \%0A\
          replace: |
            \ \
